version: 0.0
os: linux
#files:
hooks:
   BeforeInstall:
    - location: scripts/init.sh
      runas: root
    - location: scripts/load.sh
      runas: root
   AfterInstall:
    - location: scripts/restart.sh
      runas: root
